### ISSUE TITLE
Interested in Docker container?

### ISSUE THREAD

**Issue by richardkaplan** [whiskyechobravo/kerkoapp#3] opened 2019-07-19 20:01 UTC
I am working with a developer on putting the app into a Docker container to make it easier to install.  Would you be interested in that when we are done to share with others and perhaps make updates easier?

**Comment by davidlesieur** [comment] 2019-07-22 14:42
Yes, that would be very useful. You might want to collaborate on issue #4.

**Comment by davidlesieur** [comment] 2019-07-22 14:42
Duplicate of #4.

**Closed by davidlesieur** 2019-07-22 14:42 UTC
